### ISSUE TITLE
the eeror when i use docker

### ISSUE THREAD

**Issue by csufangyu** [RaptorMai/CVPR20_CLVision_challenge#1]
I get a error when I use docker，the error is:
`fangyu@Robot-DGX-Station:~/CVPR20_CLVision_challenge$ docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=2,3 -it --rm b47f54b42627
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=2,3 --compute --utility --require=cuda>=10.2 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 --pid=23648 /var/lib/docker/overlay2/060cd0ff3ef5dcbfd4ecb416ad39fa4692a5c882401125f172849a0baade8a60/merged]\\\\nnvidia-container-cli: requirement error: invalid expression\\\\n\\\"\"": unknown.`

how can i do for it?thanks

**Comment by RaptorMai** [comment]
Hi, thanks for your interest and sorry for the late reply. I am not very familiar with this docker error. If you want to reproduce the results or play with the code, you can create a virtual environment and follow the steps in the readme. Please let me know if you have any other problems.

**Comment by csufangyu** [comment]
thanks very much！ the error may be caused by CUDA  , I have solved it.方宇-------- 原始邮件 --------发件人： "Zheda (Marco) Mai" <notifications@github.com>日期： 2020年9月24日周四 中午11:55收件人： RaptorMai/CVPR20_CLVision_challenge <CVPR20_CLVision_challenge@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [RaptorMai/CVPR20_CLVision_challenge] the eeror when i use docker (#1)
Hi, thanks for your interest and sorry for the late reply. I am not very familiar with this docker error. If you want to reproduce the results or play with the code, you can create a virtual environment and follow the steps in the readme. Please let me know if you have any other problems.
